platform :ios, '11.0'
use_frameworks!

target 'iBeaconPOC' do
    pod 'Alamofire'
    pod 'CocoaLumberjack/Swift'
    pod 'LumberjackConsole'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
            config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        end
    end
end
